### ISSUE TITLE
Extract checkLinks.js into separate package

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-guidelines#152]
We should move [checkLinks.js](https://github.com/liferay/liferay-frontend-guidelines/blob/f4402a4ddbff6cd741d618d718520c8a445aac05/support/checkLinks.js) over to [liferay-npm-tools](https://github.com/liferay/liferay-npm-tools), seeing as it looks like it could prove useful in other projects (it [mostly worked in Clay](https://github.com/liferay/clay/pull/3127), for instance).

First would want to investigate the header issues that @bryceosterhaus mentioned, and I expect that using this more widely will soon bring it into contact with more edge cases, so we should be prepared for possible additional changes to follow.

**Comment by wincent** [comment]
Placeholder currently at: https://www.npmjs.com/package/liferay-link-checker

**Comment by bryceosterhaus** [comment]
One area of issue was https://github.com/liferay/clay/blob/f367b4b68d9d7a8b075e0682b3762a325b83adbc/CONTRIBUTING.md for the `What Should I Know Before I Get Started?` link

**Comment by wincent** [comment]
Closing this because I don't think we need to actually publish it any more in order to be able to use it in other projects. It's currently [here](https://github.com/liferay/liferay-frontend-projects/blob/8d9d203c6d134861d683d643577c4ca99a285bc6/guidelines/support/checkLinks.js) in [the `liferay-frontend-projects` monorepo](https://github.com/liferay/liferay-frontend-projects/blob/8d9d203c6d134861d683d643577c4ca99a285bc6/guidelines/support/checkLinks.js), and if we want to use it anywhere over there we can just move it into [the `support/packages/` directory](https://github.com/liferay/liferay-frontend-projects/tree/master/support/packages), which is "The Place" for keeping shared private packages. If Clay still wants to use it, and stays off in its own repo, we can reconsider, but closing for now seeing as we're going to mark this repo as archived/read-only soon.
