### ISSUE TITLE
DXP Minification Architecture

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-guidelines#177]
Document how does **DXP support Minification of static resources (JS, CSS...)**.

Some references:
- [frontend-js-minifier](https://github.com/liferay/liferay-portal/tree/28d106459e63294b4ea7b70bc4235b2b570d6de6/modules/apps/frontend-js/frontend-js-minifier)
- [MinifierUtil](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/portal-impl/src/com/liferay/portal/minifier/MinifierUtil.java)
- [AggregateFilter](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java)
- [ComboServlet](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java)
- [StripFilter](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/portal-impl/src/com/liferay/portal/servlet/filters/strip/StripFilter.java)
- [JSLoaderConfigServlet](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/servlet/JSLoaderConfigServlet.java)
- [JSBundleConfigServlet](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/modules/apps/frontend-js/frontend-js-bundle-config-extender/src/main/java/com/liferay/frontend/js/bundle/config/extender/internal/JSBundleConfigServlet.java)

**Comment by mateomustapic** [comment]
### **DXP Minification**

**[frontend-js-minifier](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-js/frontend-js-minifier/src/main/java/com/frontend/js/minifier)**
Liferay uses two minifiers: `GoogleJavascriptMinifier` for JS  and `YahooJavascriptMinifier` for other types.

By default, Liferay will the `GoogleJavascriptMinifier` for JS and `YahooJavascriptMinifier` for everything else. 
If we would like to use the `YahooJavascriptMinifier` for JS we can set it in your `portlet-ext.properties`.

Minifier package is located in [frontend-js-minifier](https://github.com/liferay/liferay-portal/tree/master/modules/apps/frontend-js/frontend-js-minifier/src/main/java/com/frontend/js/minifier).

----------------------
**Advantages of using minification**
- Dramatically improves site speed and accessibility
- Reduces load times and bandwidth usage on websites
- In average minifed file sizes are smaller between 48%-60% than the original files

----------------------
**Can the minification be disabled in portal?**
It is possible to disable minifier in the portal by modifying property from [portal-impl/src/portal.properties](https://github.com/liferay/liferay-portal/blob/c379f2a0f2204cf2ded7688e367ef69d72919485/portal-impl/src/portal.properties#L7644) to `minifier.enabled=false` in your `portlet-ext.properties`.

**Comment by izaera** [comment]
Warning: this documentation may overlap with the one in https://github.com/liferay/liferay-frontend-guidelines/issues/178

**Comment by izaera** [comment]
I will get the contents from @mateomustapic, reference #178, and add information on (ComboServlet, StripFilter, JSLoaderConfigServlet, JSBundleConfigServlet) to create a markdown document about this.

**Comment by mateomustapic** [comment]
> I will get the contents from @mateomustapic, reference #178, and add information on (ComboServlet, StripFilter, JSLoaderConfigServlet, JSBundleConfigServlet) to create a markdown document about this.

hey @izaera , thanks for this.
I was looking into StripFilter today, if you want I can write down my findings. 
If you want you can modify and add more details, if required.

**Comment by izaera** [comment]
@mateomustapic If they are already written just paste them here. Otherwise feel free to do what you think is better :+1:

**Comment by mateomustapic** [comment]
> @mateomustapic If they are already written just paste them here. Otherwise feel free to do what you think is better/easier 👍

Sure, pasting in this comment, so take a look. 

### **StripFilter**

`StripFilter` is responsible for caching inline JS/CSS minifier results. 

Advantages
- Significant performance improvements to the server. 
- `StripFilter` is cached on the server, which means all users will take advantage of this 

`StripFilter` can be enabled/disabled as a property in `portal.properties` by setting `com.liferay.portal.servlet.filters.strip.StripFilter` to `true/false` in your `portal-ext.properties`.

**Comment by mateomustapic** [comment]
### **Combo Servlet**
Similar to `minifiers` and `StripFilter`, the main purpose of `ComboServlet` is to make loading of Javascript files faster.
The combo servlet combines and minifies multiple JavaScript files into a bundle based on shared dependencies. 
To do that it needs the path of the files that it should combine.
—————
If we want to refresh the combination when one of `JS` files has changed, then we need to set the property below to `false`.

During development this property should be set to `true` for easier debugging.
During production this property should be set to `false` for faster performance.

`combo.check.timestamp=true/false`

If we set this property to `true`, then we can set the minimum wait interval between timestamp checks on resource files.

`combo.check.timestamp.interval=1000`

———————
In **Liferay DXP** it is used to combine resources for use by **AUI/YUI**.
Allowed file extensions by default in portal.properties are `.css` and `.js`
