### ISSUE TITLE
DXP Resource Loading Architecture

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-guidelines#178]
Document how does **DXP load and serve the different static resources (JS, CSS...)**.

Some references:
- [AggregateFilter](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/portal-impl/src/com/liferay/portal/servlet/filters/aggregate/AggregateFilter.java)
- [ComboServlet](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/portal-impl/src/com/liferay/portal/servlet/ComboServlet.java)
- [JSLoaderConfigServlet](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/servlet/JSLoaderConfigServlet.java)
- [JSBundleConfigServlet](https://github.com/liferay/liferay-portal/blob/28d106459e63294b4ea7b70bc4235b2b570d6de6/modules/apps/frontend-js/frontend-js-bundle-config-extender/src/main/java/com/liferay/frontend/js/bundle/config/extender/internal/JSBundleConfigServlet.java)

**Comment by diegonvs** [comment]
Hey @jbalsas, Does make sense adding `liferay-frontend:component` on this doc?

https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-taglib/frontend-taglib/src/main/java/com/liferay/frontend/taglib/servlet/taglib/ComponentTag.java

**Comment by jbalsas** [comment]
> Hey @jbalsas, Does make sense adding liferay-frontend:component on this doc?

Not on this one, no. This is about resource loading. We can add it elsewhere, though ;)
