### ISSUE TITLE
DXP Build Process

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-guidelines#179]
Document the architecture, subsystems and transformations that take place during **DXP build process** for frontend resources.

Some references:
- [liferay-npm-tools](https://github.com/liferay/liferay-npm-tools)
- [liferay-js-toolkit](https://github.com/liferay/liferay-js-toolkit)
- [liferay-js-themes-toolkit](https://github.com/liferay/liferay-js-themes-toolkit)

**Comment by matuzalemsteles** [comment]
I'll work on it!
