### ISSUE TITLE
Document `frontend-taglib-clay` and its relation with @clayui components

### ISSUE THREAD

**Issue by julien** [liferay/liferay-frontend-guidelines#185]
It would be useful to document how [`frontend-taglib-clay`](https://github.com/liferay/liferay-portal/tree/8de11d8e9d6424a9dc9ae8f371839e58263dc111/modules/apps/frontend-taglib/frontend-taglib-clay) works regarding our [`@clayui`](https://github.com/liferay/clay) components and what features it provides.

For example: we might want to talk about the `hydrateModule` and `propsTransformer` attributes and how to use them correctly

**Comment by bryceosterhaus** [comment]
I'll take this one

**Comment by izaera** [comment]
I'm doing https://github.com/liferay/liferay-frontend-guidelines/issues/189, so
we may need to synchronize to avoid duplication 😉.

**Comment by bryceosterhaus** [comment]
@izaera mine is more focused on using clay components, I'll send a PR today and we can hash out whats needed there

**Comment by izaera** [comment]
:+1:

**Comment by carloslancha** [comment]
Do you guys need any help with this one? Maybe we the part of what the tags renders, get hydrated, propsTransformer, additionalProps...?

**Comment by bryceosterhaus** [comment]
@carloslancha yeah feel free to add any parts you see missing. I realized I never linked my PR to this issue, here is the first iteration https://github.com/liferay/liferay-frontend-guidelines/pull/191

**Comment by julien** [comment]
Closed via #191
