### ISSUE TITLE
Document how Clay builds its pages using Gatsby

### ISSUE THREAD

**Issue by kresimir-coko** [liferay/liferay-frontend-guidelines#196]
I'd like it if we had a document of how the backbone of Clay's page creation works to ease onboarding someone new on Clay. 
Talking about `createPages.js`, `docs.js`, `onCreateNode.js`, etc.

I can scour through some of my own issues/PRs to gather some information on it, but first I wanna know your thoughts if this is a good idea to go ahead with. It would be great to have that kinda information consolidated in one place.

Also, are we supposed to be sending PRs with the documentation in Markdown, I haven't done this sort of thing before so I'm not privy to the way of things.

**Comment by jbalsas** [comment]
Hey @kresimir-coko! 

I'd say this feels like it would make more sense in the Clay repo, as part of our `CONTRIBUTING.md` or as a way to onboard people looking to contribute there.

**Comment by wincent** [comment]
> I can scour through some of my own issues/PRs to gather some information on it, but first I wanna know your thoughts if this is a good idea to go ahead with.

Having barely looked at it, I will leave it for others to opine. 😀 

> It would be great to have that kinda information consolidated in one place.

Yes, and if it is Clay-specific, I would think it would best belong in the Clay repo (like I see Chema just said, as his comment popped in while I was typing this).

> Also, are we supposed to be sending PRs with the documentation in Markdown, I haven't done this sort of thing before so I'm not privy to the way of things.

Wherever it goes, yes... Markdown.

**Comment by bryceosterhaus** [comment]
Sounds good to me. I would err on the side of linking back to gatsby often, rather than re-documenting gatsby features. If we can focus more on Clay's specific flow of creation, the better.

**Comment by kresimir-coko** [comment]
Alright, I'll open this issue in Clay then, thanks for the feedback! 👍
