### ISSUE TITLE
checkLinks.js doesn't know how to check heading links to other local files

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-guidelines#206]
As seen in the CI failure on #201, which adds our first local link that includes a heading reference (eg `other_file.md#blah`).

From Slack:

> this is what I see:
>
> ```
> dxp/javascript_minification.md: No file/directory found for local target: dxp/resource_serving.md
> dxp/javascript_minification.md: No file/directory found for local target: dxp/resource_serving.md#aggregate-filter
> ```
>
> after a rebase, I see:
>
> ```
> dxp/javascript_minification.md: No file/directory found for local target: dxp/resource_serving.md#aggregate-filter
> ```
>
> so that means the tool doesn't know how to look for anchors in local files (other than the current one)

@izaera already has a fix for this (calling `checkInternal` from `checkLocal`).

**Comment by izaera** [comment]
> @izaera already has a fix for this (calling checkInternal from checkLocal).

![recursive](https://media.giphy.com/media/l4FGEj3ORYD3pt67K/giphy.gif)
