### ISSUE TITLE
Document Top Head Dynamic Includes

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-frontend-guidelines#210]
- [portal-kernel/DynamicInclude.java](https://github.com/liferay/liferay-portal/blob/973e6199844436c22d237e2daf4821d0f9af5362/portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/DynamicInclude.java)
- [frontend-js-top-head-extender-api/TopHeadResources.java](https://github.com/liferay/liferay-portal/blob/cc9be6b4dbf289902cb8edb89f1b38b1334e6284/modules/apps/frontend-js/frontend-js-top-head-extender-api/src/main/java/com/liferay/frontend/js/top/head/extender/TopHeadResources.java)
- [portal-kernel/TagDynamicInclude.java](https://github.com/liferay/liferay-portal/blob/973e6199844436c22d237e2daf4821d0f9af5362/portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/TagDynamicInclude.java) (?)
- [html-top tag](https://github.com/liferay/liferay-portal/blob/b87113b5cfe9217b8327ce60c97579938c7fc6dd/util-taglib/src/com/liferay/taglib/util/HtmlTopTag.java)
- [OutputData](https://github.com/liferay/liferay-portal/blob/b93f433935ed9006ed972507dabf4f4d8c3b5c7c/portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/util/OutputData.java#L34)
- [ScriptData](https://github.com/liferay/liferay-portal/blob/f587ba0fb69ec3f113e57b96ae59e6796d8f3a52/portal-kernel/src/com/liferay/portal/kernel/servlet/taglib/aui/ScriptData.java#L43-L42)

The last two are probably a bit off-topic, but as they are related I will put their documentation here and we can then refactor and merge it with the other resource serving docs.

**Comment by bryceosterhaus** [comment]
Also used for [svg4everybody](https://github.com/liferay/liferay-portal/blob/2f37a22bf2dbffae0e1ac7cd3a98afaeef2b5c48/modules/apps/frontend-js/frontend-js-svg4everybody-web/src/main/java/com/liferay/frontend/js/svg4everybody/web/internal/servlet/taglib/SVG4EverybodyTopHeadDynamicInclude.java)
