### ISSUE TITLE
Revert recommendation to prefer ".ts" over ".tsx"

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-guidelines#24]
In https://github.com/liferay/liferay-frontend-guidelines/pull/8 I recommended ".ts" over ".tsx" without actually trying it — I was invalidly generalizing my experience with ".js" and ".jsx". [This doc](https://www.typescriptlang.org/docs/handbook/jsx.html) leads me to believe that won't actually work because it says:

> In order to use JSX you must do two things.
>
> - Name your files with a .tsx extension
> - Enable the jsx option

I had thought you only had to enable the second option... So, let's double check that the documentation is actually right and if it is, update the recommendation.

**Comment by bryceosterhaus** [comment]
I also ran into this initially with Clay. I think typescript tends to be a bit more explicit with its file extensions and expects `.tsx` when working with JSX. I don't remember finding this "Enable the jsx option", but if its possible to do that then I am all game for just using `.ts`

**Comment by kienD** [comment]
I also ran into the issue where JSX wasn't parsed in `.ts` files even though I enabled the `jsx` option.  It only worked once I explicitly added the `.tsx` extension.
