### ISSUE TITLE
Consider trying out Probot in this repo

### ISSUE THREAD

**Issue by wincent** [liferay/liferay-frontend-guidelines#36]
I'd like to use "Probot" to enforce correct pull request titles in our frontend repos. Maybe this one would be a good repo to try it out in?

- https://github.com/probot/semantic-pull-requests
- https://github.com/apps/semantic-pull-requests
- https://probot.github.io/

We're using the [Conventional Commits format in our commit messages](https://github.com/liferay/liferay-frontend-guidelines/blob/92450cec499938a22bbef42872851fa8710121ef/guidelines/contributing/commit_messages.md), and the guidance is that we do the same for the PR titles themselves.

This is useful because when you click "Merge" in GitHub, the PR title winds up in the merge commit, and we can use those merge commits to generate a changelog. (For an example of this in practice, see the [liferay-js-themes-toolkit CHANGELOG](https://github.com/liferay/liferay-js-themes-toolkit/blob/8081b88aec8c79373b2550384998a901ad99e0f6/CHANGELOG.md)).

#35 is an example of a PR that had a good commit message but the PR title was just "master", so when we merged it, the merge commit (92450cec499938) just contained the word "master" in the body. We aren't actually generating a changelog in this repo, so it doesn't matter, but I think it would be nice to try out the bot here if we can, and if it works well, apply it to other repos too, just so that we have a consistent pattern for how we ship changes across the board.

**Comment by bryceosterhaus** [comment]
I like the idea, but it also seems kind of strange to generate changelog based on PR titles. One primary reason for this is that PR titles will likely be the same as the commit or something generic. Would it make more sense to generate change logs based on issue titles instead?

**Comment by matuzalemsteles** [comment]
Yes I think it wise to point to the issues and also add reference to the PR that corrected this. Just the ID would be enough.

**Comment by julien** [comment]
I think it's worth the try.  After all there's nothing to loose.
We can always decide to continue using it or not.

**Comment by wincent** [comment]
The virtue of using the PR titles is that GitHub puts those in the bodies of the merge commits that it creates. This means that the changelog can be generated simply by looking at the commit history, specifically the merge commits, and there is no need to hit the GitHub API (which winds up causing all many of problems with rate-limiting; and the tool we were using, `github_changelog_generator` was woefully ill-equipped to figure out which issues/PRs actually belonged to which release, and to which branch — I wrote up all the ways it worked terribly [here](https://github.com/liferay/liferay-js-themes-toolkit/issues/221)).

> One primary reason for this is that PR titles will likely be the same as the commit or something generic.

This to me just means that we need to write better PR titles. Once you know that any given PR is going to wind up in the changelog, it incentivizes you to use a good title. Something that sadly doesn't happen much in a certain other repo that we all know...

<img width="777" alt="Pull_Requests_·_brianchandotcom_liferay-portal" src="https://user-images.githubusercontent.com/7074/59950812-60f1f700-9477-11e9-8d4d-b07aaa5f8119.png">

**Comment by jbalsas** [comment]
I've requested ProBot to be installed here... just to give it a try :)

**Comment by bryceosterhaus** [comment]
> This to me just means that we need to write better PR titles

 +1

**Comment by wincent** [comment]
The Semantic Pull Requests bot is now active here and in (most?) of our other active frontend repos and working pretty well apart from [one small issue](https://github.com/probot/semantic-pull-requests/issues/51) wherein it doesn't yet validate types with a trailing exclamation point to indicate breaking changes.
