### ISSUE TITLE
Use TypeScript in portlets

### ISSUE THREAD

**Issue by brunofarache** [liferay/liferay-frontend-guidelines#37]
We are creating a portlet in portal and would like to use TypeScript.

Benefits of using TypeScript are well known, to list a few:

- Static typing and type inference, errors are caught in build time.
- Better tooling integration, with code completion and documentation.

Since it's being used in Clay, I think it's a natural path to be used in our portlets as well?

**Comment by jbalsas** [comment]
Hey @brunofarache, we are indeed starting to use TypeScript in Clay as a way to become familiar with it in a controlled scenario with hopes to roll it out at some point in a more global way.

@bryceosterhaus and @matuzalemsteles can probably provide more details about their experience.

I think it's looking good, and the benefits, as you say, are well known. At the same time, these don't come for free and sometimes I've seen conversations focused merely on the right types and how to properly express something in TS.

As natural as it feels, I think at this point **I'm more inclined to discourage global usage** in portlets until we have better adoption and can offer better support. My main concerns are:
- Cognitive overhead. We're already planning to move to React, and moving to TS at the same time adds additional cognitive overhead to those frontends that don't know it yet and will need to spend some time getting comfortable with it with little help of other examples and highly trained co-workers.
- Maintainability. Even if some team has someone experienced enough to succeed at scale, I think it can become a risk for future maintainability to roll out TS just for that specific team as we won't be able to fully support them.
- Supportability. I'm not confident we can safely pass such big changes and expect them to be supported as new versions are backported and released. Same way we need to train our product engineers we need to help support engineers be ready for it. At this point, I wouldn't feel comfortable dumping this on them.

This being said, until we feel comfortable with a general recommendation, we'd be willing to allow a team to spearhead efforts in this direction considering that:
- It is aligned with our future direction as discussed in our Frontend Gathering in January
- The Frontend Infra team might only be able to offer limited support and guidance throughout the initial steps
- The team understands the risks it's taking at being the first to walk down this path (common issues encompass flaky build process, test infrastructure, source formatting, lack of patterns and components...)
- The team should be responsible for helping infra put together at least the minimal requirements needed to make this succeed globally so we can move in the right direction (training materials, support enablement...)
- The team needs to ship a product and infra tasks should not come in the way

We did this with the Personalization team in the previous version and are now trying to consolidate the React experience learnt there to roll it out globally.

I'll document this as a guideline, but I think we can have a conversation if you really want to be the first ones to walk down this path :)

**Comment by wincent** [comment]
My 2¢.

I'd love to see us using TypeScript in the liferay-portal repo, but I don't think the "time is ripe" yet, even if framed in terms of an experimental/exploratory/spearhead effort with a single team.

We need to wrap up some very large in-progress roll-outs first (Yarn, liferay-npm-scripts, Prettier, ESLint etc) and make significant progress on others (eg. React) before we can introduce a another pretty big paradigm shift without raising the level of entropy and variation beyond a sustainable level. And by "roll-out", it's not just getting those things into the liferay-portal master branch, but also stabilizing them and backporting them to prior releases (insofar as that is practically possible), so that the codebases on the prior release branches don't become totally alien and impossible to backport fixes and other features to.

So this is a very interesting question which I'd like to periodically check in and ask, "are we ready yet?", but I don't think we are right now. In the meantime, things like the Clay experiment, which take place in a standalone GitHub repo with a separate build and CI process, seem like great ways to start getting value out of and learning about static typing.

**Comment by brunofarache** [comment]
Thanks for your input, @jbalsas and @wincent!

We are creating a new portlet and backporting wouldn't be a concern, since it will be available in 7.3 only.

We could apply to that portlet only, as an experiment, and then, if at some point we decide to rollout to other portlets, we could add support to liferay-npm-scripts. In this case, we would need to add some devDependencies. 

Would it be possible to use it in such a way it doesn't affect anything else other than our portlet? Or is it something that will inherently affect other stuff? My understanding is that it would only affect the portlet build process and not the portal's runtime, correct?

Another approach would be to develop our React components in a separate repo and reuse in portal, just like you are doing with Clay and have more freedom to do whatever we want. But that's just a way of not facing with the real problem.

**Comment by brunofarache** [comment]
Closing this issue. Too many wise people saying I'll be in trouble.

I was going to create an issue to use Svelte but gave up on that too. :P

@wincent since Clay is using a newer version of React, you may need to upgrade the Segments portlet soon. I will use the same version they are using since they are a dependency of mine.

I'm also interested in getting to know how I can speed up the development process. I saw you have some watch scripts but couldn't get it to work. I may bug you next week about this. thanks!

**Comment by jbalsas** [comment]
Spoiler alert, @brunofarache: https://github.com/jbalsas/liferay-portal/pull/1810 😉 

We hope to roll out some initial React goodies together with the first Clay milestones in the next weeks. I also plan to write a post in Loop with our current state and short/mid/long term plans for Frontend Development very soon to help get us all in sync.

Thanks a lot for understanding... and it's great to see you join the frontend side now! 😘

**Comment by brunofarache** [comment]
Thanks @jbalsas!

I've been playing around with the new Clay already by building it from source and linking to my portlet:

https://github.com/brunofarache/liferay-portal/tree/clay-table/modules/apps/data-engine/data-engine-web/src/main/resources/META-INF/resources/js/components

I was able to build a `SearchContainer` component, by combining ClayTable, ClayPagination and a search input field. It would be nice to move it to a shared module later on.

Going to change it to use milestone 1 you just published and send the first PR next week!

The most critical issue the Workflow team has faced was the incompatibility between react-router and Senna. Even though `HashRouter` works fine, the URL looks ugly.

**Comment by jbalsas** [comment]
I think @matuzalemsteles had some ideas about how to approach this that we can revisit if navigation is really necessary
