### ISSUE TITLE
Standardize React Drag&Drop strategy

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-frontend-guidelines#39]
As we start to move into React realm, we need to start standardizing some common strategies.

The goal of this ticket is to discuss Drag&Drop libraries. Some options out there are:
- [react-dnd](https://github.com/react-dnd/react-dnd/)
- [react-beautiful-dnd](https://github.com/atlassian/react-beautiful-dnd)
- ...

The personalization team is [already using react-dnd](https://github.com/liferay/liferay-portal/blob/master/modules/apps/segments/segments-web/package.json#L10-L11), so that's the one we will start offering, but the moment to decide should be now.

Calling out here in case they want to provide feedback and/or pros/cons lists based on their experience or previous research: @p2kmgcl, @andresfulla, @bryceosterhaus, @sandrodw3, @wincent, @matuzalemsteles... feel free to bring in anyone that could offer additional insight

**Comment by andresfulla** [comment]
@thektan might know about this.

From my understanding `react-dnd` is mush more powerful and flexible, and `react-beautiful-dnd` is less flexible, has less options and it's focused on lists _(performance I guess)_.

**Comment by matuzalemsteles** [comment]
I do not have a preferred choice but I would be fine with some of the two. But just adding some notes to reflect on these decisions.

I really like what I see in `react-beautiful-dnd` 'It's very good for user experience and has an excellent collision mechanism, dealing with many known dnd, performance, and UX issues.

One plus point is that it is maintained by the Atlassian, they pretty much use the dnd in all products and it keeps a person in charge to keep it dedicated in evolving ... I would recommend reading the maintainer about the time he spent on the dnd (https://dev.to/alexandereardon/what-does-react-beautiful-dnd-cost-to-maintain-52e8).

The documentation is very complete and has many articles of the project itself showing good practices, I think I say the same for `react-dnd`... But really it for list is far more powerful than `react-dnd` and more natural in terms of UX... But it also does not stop you from doing other things: https://checkers-game.netlify.com/

- https://react-beautiful-dnd.netlify.com - Storybook

Probably Dnd with list is what I see the most in the portal, so if we want something to solve this problem possibly a great candidate would be `react-beautiful-dnd`.I see that `react-dnd` is very low level and you will have to deal with many problems that a dnd delivers and maybe write a lot... But it's just my opinion of what I see.

**Comment by wincent** [comment]
I have zero experience with either library, so please apply a 0.1x multiplier to these observations:

* It *might* be the case that we could start with a lower level thing like react-dnd, and then if we identify common patterns that we want to make easier, we could add a layer of wrapping around it to make those ergonomic; on the other hand, if we run into a limitation in react-beautiful-dnd that we wish to circumvent, that may not be possible via mere wrapping.
* On the flip side, we should bear in mind that unless we race to start adding React-powered drag-and-drop functionality all over liferay-portal overnight, the cost of making a "mistake" here and choosing the "wrong" library might not actually be that high. We will probably have figured out what is best for us before we have too many usage sites, and switching wouldn't be prohibitively expensive.

**Comment by thektan** [comment]
Similar to https://github.com/liferay/liferay-frontend-guidelines/issues/39#issuecomment-505365566, `react-dnd` is very flexible to implement any type of drag and drop behavior you want. There's a lot of manual implementation required so https://github.com/liferay/liferay-frontend-guidelines/issues/39#issuecomment-505481511 about wrapping common patterns would be ideal for following lexicon design patterns.

`react-beautiful-dnd` on the other hand has a ton of features bundled with it, but it is made for a specific use case of kanban board/list-like drag and drop. For example, the copy/paste drag and drop we were building in the Segments Editor use case is not supported (https://github.com/atlassian/react-beautiful-dnd/issues/216). It also enforces its own [design patterns](https://github.com/atlassian/react-beautiful-dnd/blob/master/docs/about/design-principles.md) which might not align with lexicon patterns.

As a recap: For list-type drag and drop, `react-beautiful-dnd` is great, but for all the other edge cases, `react-dnd` would fill those in. If we had to only choose 1 though, `react-dnd` would be the most customizable to fit any need--use case and design-wise.

**Comment by p2kmgcl** [comment]
I have the same thoughts than @thektan, I think those libraries should not be exclusive, it depends a lot on the result you want to present, and on my experience I found no drag&drop library that has enough configuration for not needing to write code.

Even more, I am not sure if choosing a react-specific library for drag&drop is even necessary. I used metal-drag-drop, dragula, react-dnd and react-beautiful-dnd and they all work the same: defining some drag sources and some drop areas. The only different (I felt) of using these with react you use a wrapper component, and with non-react you use dom selectors. At the end, defining the behavior of the drag&drop will be almost the same code.

**Comment by wincent** [comment]
Ok, just to summarize the current status: as @jbalsas says [here](https://issues.liferay.com/browse/LPS-99879):

> We more or less already decided on react-dnd, which also got legal clearance from Matija Suklje at https://issues.liferay.com/browse/FOSS-52, so we should properly wrap this up and document it in the guidelines for future reference.

Other relevant comments:

- "react-dnd is mush more powerful and flexible" (@andresfulla)
- "If we had to only choose 1 though, `react-dnd` would be the most customizable to fit any need" (@thektan)

And we're using it already. I'm going to ship a tiny document that links to this discussion and then move on with the update in liferay-portal.

**Comment by bryceosterhaus** [comment]
@jbalsas any idea if there is a super simple type of dnd component that we use in portal? I was thinking it might be helpful to create a simple high-level dnd component in clay. Assuming its needed somewhere.

**Comment by jbalsas** [comment]
Hey @bryceosterhaus, that's probably a great idea, although I'm not sure we have enough information for now...

You can see current usages in the [Drag and Drop - See also](https://github.com/liferay/liferay-frontend-guidelines/blob/f98afdf69397d7a5dc625f8c4809dac5d7ef706f/dxp/drag_and_drop.md#see-also) section of the guidelines. I think they're all pretty simple, but maybe we can start gathering some info from there.

@thektan, would you be so kind as to let us know when your code is in or to point us to some sources so @bryceosterhaus can think if there's something we could/should provide on our side?

**Comment by thektan** [comment]
@bryceosterhaus For result rankings, we're using drag and drop here: https://github.com/thektan/liferay-portal-ee/tree/LPS-88817_Search_Tuning_Result_Rankings/modules/private/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/resources/META-INF/resources/js/components/list
- Item.es.js
- ItemDragLayer.es.js
- ItemDragPreview.es.js

DragLayer and DragPreview are pretty boilerplate-y so that could be something that would nice to have provided. Maybe with hooks in the newer version of react-dnd things are more simplified too.
