### ISSUE TITLE
Single return policy

### ISSUE THREAD

**Issue by andresfulla** [liferay/liferay-frontend-guidelines#6]
`liferay-npm-scripts format` no longer reports multiple returns. **I'm wondering if that's intended, and if that's here to stay.**

In my opinion, I'd rather have the option to chose if I need several returns, and trust teammates PRs to avoid any misuse. More often than not I found myself twisting code to comply with single return rule.

**Comment by boton** [comment]
> I'd side on allowing it for JS too from now on.

👯🎉🎉🎉👯‍♂ 


I really miss the [early return](https://codeburst.io/code-js-in-stlye-early-return-3462323e30d1) pattern.

**Comment by jbalsas** [comment]
This is already done. Our eslint config is updated and enabled and we already allow multiple returns. I don't think we need to document this any further, so let those returns free!
